// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $nuevo_contacto from "./routes/nuevo-contacto.tsx";
import * as $ChatBox from "./islands/ChatBox.tsx";
import * as $MessageInput from "./islands/MessageInput.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/nuevo-contacto.tsx": $nuevo_contacto,
  },
  islands: {
    "./islands/ChatBox.tsx": $ChatBox,
    "./islands/MessageInput.tsx": $MessageInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
